import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css' // 모든 페이지에 적용되는 CSS
import styles from './page.module.css'; // 해당 페이지에서만 적용될 CSS

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.container}>
          {children}
        </div>
      </body>
    </html>
  )
}
